apiVersion: v1
kind: Pod
metadata:
  name: gpu-cli-1
  annotations: {}
spec:
  containers:
  - name: nvidia-smi
    image: nvidia/cuda:12.5.0-devel-ubuntu22.04
    command:
    - bash
    - -c
    - |
      nvidia-smi
      apt-get update -y && \
      DEBIAN_FRONTEND=noninteractive apt-get install -y --allow-unauthenticated cuda-demo-suite-12-5
      /usr/local/cuda/extras/demo_suite/deviceQuery
      /usr/local/cuda/extras/demo_suite/vectorAdd
      /usr/local/cuda/extras/demo_suite/bandwidthTest --device=all --csv
      /usr/local/cuda/extras/demo_suite/busGrind -a
    resources:
      limits:
        nvidia.com/gpu: 1
  restartPolicy: Never
